# Uncommented PersistentVolume and PersistentVolumeClaim for testing
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: ftp-data-pv
#   namespace: selenium
# spec:
#   capacity:
#     storage: 1Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: C:/docker-ftp-folder
---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: ftp-data-pvc
#   namespace: selenium
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftp-server
  namespace: selenium
  labels:
    app: ftp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftp-server
  template:
    metadata:
      labels:
        app: ftp-server
    spec:
      containers:
      - name: ftp-server
        image: stilliard/pure-ftpd
        imagePullPolicy: Never
        ports:
        - containerPort: 21
        - containerPort: 30000
        - containerPort: 30001
        - containerPort: 30002
        - containerPort: 30003
        - containerPort: 30004
        - containerPort: 30005
        - containerPort: 30006
        - containerPort: 30007
        - containerPort: 30008
        - containerPort: 30009
        env:
        - name: FTP_USER_NAME
          value: "user1"
        - name: FTP_USER_PASS
          value: "password1"
        - name: FTP_USER_HOME
          value: "/home/user1"
        # Commented out volumeMounts since PVC is removed
        # volumeMounts:
        # - mountPath: /home/user1
        #   name: ftp-data
      # Commented out volumes since PVC is removed
      # volumes:
      # - name: ftp-data
      #   persistentVolumeClaim:
      #     claimName: ftp-data-pvc
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: ftp-service
  namespace: selenium
spec:
  selector:
    app: ftp-server
  type: NodePort
  ports:
    - name: ftp-control
      protocol: TCP
      port: 21
      targetPort: 21
    - name: ftp-passive-30000
      protocol: TCP
      port: 30000
      targetPort: 30000
      nodePort: 30000
    - name: ftp-passive-30001
      protocol: TCP
      port: 30001
      targetPort: 30001
      nodePort: 30001
    - name: ftp-passive-30002
      protocol: TCP
      port: 30002
      targetPort: 30002
      nodePort: 30002
    - name: ftp-passive-30003
      protocol: TCP
      port: 30003
      targetPort: 30003
      nodePort: 30003
    - name: ftp-passive-30004
      protocol: TCP
      port: 30004
      targetPort: 30004
      nodePort: 30004
    - name: ftp-passive-30005
      protocol: TCP
      port: 30005
      targetPort: 30005
      nodePort: 30005
    - name: ftp-passive-30006
      protocol: TCP
      port: 30006
      targetPort: 30006
      nodePort: 30006
    - name: ftp-passive-30007
      protocol: TCP
      port: 30007
      targetPort: 30007
      nodePort: 30007
    - name: ftp-passive-30008
      protocol: TCP
      port: 30008
      targetPort: 30008
      nodePort: 30008
    - name: ftp-passive-30009
      protocol: TCP
      port: 30009
      targetPort: 30009
      nodePort: 30009
