apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-node-edge
  namespace: selenium
  labels:
    app: selenium-node-edge
spec:
  replicas: 2
  selector:
    matchLabels:
      app: selenium-node-edge
  template:
    metadata:
      labels:
        app: selenium-node-edge
    spec:
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      - name: videos
        emptyDir: {} # Volume to store video files
      containers:
      - name: selenium-node-edge
        image: selenium/node-edge:4.11.0
        ports:
          - containerPort: 5555
        volumeMounts:
          - mountPath: /dev/shm
            name: dshm
          - mountPath: /videos
            name: videos # Mount the shared volume for video storage
        env:
          - name: SE_EVENT_BUS_HOST
            value: "selenium-hub"
          - name: SE_EVENT_BUS_SUBSCRIBE_PORT
            value: "4443"
          - name: SE_EVENT_BUS_PUBLISH_PORT
            value: "4442"
          - name: SE_ENABLE_VIDEO
            value: "true" # Enable video recording
        resources:
          limits:
            memory: "500Mi"
            cpu: ".5"

